apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170026741
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170026741
    app.kubernetes.io/part-of: test-app-170026741
  name: java-quarkus-170026741
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170026741
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170026741
    spec:
      containers:
      - image: quay.io/hacdev/ftjmd1va-tenant/test-app-170026741/java-quarkus-170026741@sha256:88913e14d636d6b37a26b14faa93eb05dd089e3a9031ac4372f00fecef497870
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
