apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170026741
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/ftjmd1va-tenant/test-app-170026741/java-quarkus-170026741@sha256:88913e14d636d6b37a26b14faa93eb05dd089e3a9031ac4372f00fecef497870
        name: my-java-quarkus
        resources: {}
status: {}
